USE [C:\USERS\TOLUNAY\DOCUMENTS\SPORR.DB.MDF]
GO

/****** Object: Table [dbo].[ödeTbl] Script Date: 30.05.2023 14:44:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE [dbo].[ödeTbl];


